### ISSUE TITLE
TypeError: in this environment the sources for assign MUST be an object

### ISSUE THREAD

**Issue by JuanCAlpizar** [jkomyno/react-native-animated-checkbox#1]
I keep getting this error by using the props that are documented on the readme. The lack of an example doesn't help much, but I'd take a wild guess this is related to the spread operator you're using to assign the styles in the plugin code

**Comment by jkomyno** [comment]
Thanks for having opened the first issue! Can you please tell me which version of React Native are you running? And also, can you please paste a minimal snippet of code to understand how you're calling the <CheckBox /> component? Thanks.

And btw, sorry for the current lack of an example.

**Comment by jkomyno** [comment]
Please try installing `react-native-animated-checkbox@1.0.2`.

**Comment by JuanCAlpizar** [comment]
@jkomyno thanks for your feedback :) I'm using yarn to add it to my project, which is automatically downloading the 1.0.2 version to the project. 

after installing, I try to import it this way, I assumed it was the right one because `Checkbox` is the most common name and it's the default class you export on your `index.js`

`import Checkbox from 'react-native-animated-checkbox';`

Then I added it to my View changing my previous `Checkbox` component with this one, using this syntax:

    <View style={styles.rememberCredentials}>                        
        <Checkbox 
            checked={false}
            color="#F26F6F"
            style={styles.defaultStyle} 
            onPress={() => {}}
        />
        <Text style={styles.rememberCredentialsText}>Remember Password</Text>
    </View>

This is my complete `styles` object:

    const styles = StyleSheet.create({
        headerImage: {
            flex: 1,
            marginTop: 35,
            marginBottom: 35,
            justifyContent: 'center',
            alignItems: 'center'
        },
        loginForm: {
            flex: 2,
            marginTop: 15
        },
        actionButtonArea: {
            justifyContent: 'center',
            alignItems: 'center'
        },
        loginSingupText: {
            color: '#fff',
            marginTop: 15,
            marginBottom: 10,
            textAlign: 'center'
        },
        rememberCredentials: {
            flexDirection: 'row', 
            marginTop: 10,
            marginBottom: 15,
            marginLeft: 5
        },
        rememberCredentialsText: {
            color: '#fff',
            marginLeft: 5
        },
        defaultStyle: {
            backgroundColor: 'transparent',
            margin: 2,
            padding: 1,
            borderRadius: 0,
            borderWidth: 2
        }
    });

As you can see, the styles is the same as the one in the readme except for the value which is obtained from the `props` object. I also added an empty `onPress` event in the case there was a syntax error, which wasn't the case.

I tried to setup a snack with the code but it wasn' t recognizing the plugin so the error output is different. I did set it up on a project I'm currently working on with the code posted above, ran it directly on my phone and this is a screenshot of the error output:

![image](https://user-images.githubusercontent.com/2028118/32705322-633a2d56-c7d8-11e7-9652-2c637b8677e7.png)

I'm running the latest sdk from Expo, running `react-native --version` inside my project folder returns this:

    react-native --version
    react-native-cli: 2.0.1 
    react-native: 0.49.3

Edit: I also tried to add `iconName='check'` and `iconSize={15}` to the props above but the output was the same

**Comment by jkomyno** [comment]
I can't seem to reproduce the error: https://snack.expo.io/rJb4eAUyz

**Comment by JuanCAlpizar** [comment]
Well, now this is weird: I just tried to run that snack and didn't work on the emulator, and when I ran it on my device I got the 'requiring unknown module' I mentioned before 😕 

![image](https://user-images.githubusercontent.com/2028118/32723537-6f5a0e84-c833-11e7-9d69-92d30694eb97.png)

**Comment by JuanCAlpizar** [comment]
@jkomyno  same output from the emulator: 
![image](https://user-images.githubusercontent.com/2028118/32723677-fae568a4-c833-11e7-9707-b8251596656a.png)

silly question, does it runs on both platforms or is it just runs on iOS? I may be making a silly assumption

**Comment by turfaa** [comment]
I have fixed this in #3 

This is because you try to access the style created by StyleSheet.create()
